// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIstAUn3AbbavWpNt3XsEsaTbyCv1zRRo',
    appId: '1:938551042717:web:ab2048bdaca0d24f6e2a74',
    messagingSenderId: '938551042717',
    projectId: 'aclapp-58c7d',
    authDomain: 'aclapp-58c7d.firebaseapp.com',
    storageBucket: 'aclapp-58c7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1iYKD3-l7M2M506uKO_X9OPZIfQtXoA',
    appId: '1:938551042717:android:afdcc6e302ebfc5c6e2a74',
    messagingSenderId: '938551042717',
    projectId: 'aclapp-58c7d',
    storageBucket: 'aclapp-58c7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFU8W9wslpzYM9ZzDWSiVK44aHQRUpVIk',
    appId: '1:938551042717:ios:5be5999a2b10de806e2a74',
    messagingSenderId: '938551042717',
    projectId: 'aclapp-58c7d',
    storageBucket: 'aclapp-58c7d.appspot.com',
    iosBundleId: 'com.example.aclApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFU8W9wslpzYM9ZzDWSiVK44aHQRUpVIk',
    appId: '1:938551042717:ios:5be5999a2b10de806e2a74',
    messagingSenderId: '938551042717',
    projectId: 'aclapp-58c7d',
    storageBucket: 'aclapp-58c7d.appspot.com',
    iosBundleId: 'com.example.aclApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIstAUn3AbbavWpNt3XsEsaTbyCv1zRRo',
    appId: '1:938551042717:web:ef52316e7c8ead6b6e2a74',
    messagingSenderId: '938551042717',
    projectId: 'aclapp-58c7d',
    authDomain: 'aclapp-58c7d.firebaseapp.com',
    storageBucket: 'aclapp-58c7d.appspot.com',
  );
}
